### ISSUE TITLE
Formatted log messages are handled weirdly

### ISSUE THREAD

**Issue by miikka** [viesti/timbre-json-appender#2]
If you log like this with the `*f` variants of logging calls:

```clojure
(log/infof "%s %s" foo bar)
```

You'll get a result where message is empty and args is essentially `{foo bar}`.

**Comment by viesti** [comment]
Hmm, have to dig into Timbre default log formatter a bit, it might contain logic that handles this, since argument list now contains data meant for format string.

**Comment by viesti** [comment]
Added handling of formatted log messages via `String/format`, but excess arguments that follow the format string are now discarded. This goes against the style of mixing log message and data so it would make sense to parse the format string for the number of placeholders in order to add rest of the arguments as fields to the JSON formatted log string.

**Comment by viesti** [comment]
Wen't and pushed a commit that counts format specifiers in the format string and includes the rest of the logging call arguments in the `args` field. At least data is not lost now :)

**Comment by viesti** [comment]
Doing issue cleaning, there's even a [test for the format string use](https://github.com/viesti/timbre-json-appender/blob/master/test/timbre_json_appender/core_test.clj#L44-L51) so closing this issue :)
